language: objective-c
osx_image: xcode9

env:
  - CODECOV_TOKEN=052f3a87-aeca-4e0b-8891-a39dd3338160


script:
  - set -o pipefail
  - xcodebuild build test -scheme CountedSet -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty
  - bash <(curl -s https://codecov.io/bash)
